/*
import bythos;


fn void loading() @test {
  bythos::init();

  //Mesh m = mesh::load("resources/Puffmin.obj");
  bythos::upload_file("resources/Puffmin.obj");

  while (!bythos::should_close()) {
    render::draw_mesh("Mesh_0", scale:{0.1,0.1,0.1});
    render::draw_mesh("Mesh_1", scale:{0.1,0.1,0.1});
    render::draw_mesh("Mesh_2", scale:{0.1,0.1,0.1});
    render::draw_mesh("Mesh_3", scale:{0.1,0.1,0.1});
    bythos::draw();
  }

  bythos::clean();
  assert(false);
}
*/
