

import std::math;
import bythos;


fn void set_uniforms() @test {
  Shader s = shader::compile();

  /*
  shader::set_uniform{int}  (&s, "test", 0);
  shader::set_uniform{float}(&s, "test", 0.1);
  shader::set_uniform{Vec2f}(&s, "test", {0,0});
  shader::set_uniform{Vec3f}(&s, "test", {0,0,0});
  shader::set_uniform{Vec4f}(&s, "test", {0,0,0,0});
  shader::set_uniform{Matrix4f}(&s, "test", {});
  shader::set_uniform{Texture}(&s, "test", {});
  */

  //assert(false,"End");
}

